// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDeControleDeTCCs.Models;

namespace SistemaDeControleDeTCCs.Migrations
{
    [DbContext(typeof(ContextoGeral))]
    [Migration("20200408004037_relacionamentos02")]
    partial class relacionamentos02
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaDeControleDeTCCs.Models.Banca", b =>
                {
                    b.Property<int>("BancaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("datetime2");

                    b.HasKey("BancaId");

                    b.ToTable("Banca");
                });

            modelBuilder.Entity("SistemaDeControleDeTCCs.Models.Calendario", b =>
                {
                    b.Property<int>("CalendarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataApresentacao")
                        .HasColumnType("datetime2");

                    b.HasKey("CalendarioId");

                    b.ToTable("Calendario");
                });

            modelBuilder.Entity("SistemaDeControleDeTCCs.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescStatus")
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("StatusId");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("SistemaDeControleDeTCCs.Models.Tcc", b =>
                {
                    b.Property<int>("TccId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BancaId")
                        .HasColumnType("int");

                    b.Property<int?>("CalendarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("TccId");

                    b.HasIndex("BancaId");

                    b.HasIndex("CalendarioId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tccs");
                });

            modelBuilder.Entity("SistemaDeControleDeTCCs.Models.TipoUsuario", b =>
                {
                    b.Property<int>("TipoUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescTipo")
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("TipoUsuarioId");

                    b.ToTable("TipoUsuario");
                });

            modelBuilder.Entity("SistemaDeControleDeTCCs.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("TipoUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("cpf")
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SistemaDeControleDeTCCs.Models.Tcc", b =>
                {
                    b.HasOne("SistemaDeControleDeTCCs.Models.Banca", "Banca")
                        .WithMany("Tccs")
                        .HasForeignKey("BancaId");

                    b.HasOne("SistemaDeControleDeTCCs.Models.Calendario", "Calendario")
                        .WithMany("Tccs")
                        .HasForeignKey("CalendarioId");

                    b.HasOne("SistemaDeControleDeTCCs.Models.Status", "Status")
                        .WithMany("Tccs")
                        .HasForeignKey("StatusId");

                    b.HasOne("SistemaDeControleDeTCCs.Models.Usuario", "Usuario")
                        .WithMany("Tccs")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("SistemaDeControleDeTCCs.Models.Usuario", b =>
                {
                    b.HasOne("SistemaDeControleDeTCCs.Models.TipoUsuario", "TipoUsuario")
                        .WithMany("Usuario")
                        .HasForeignKey("TipoUsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
